### ISSUE TITLE
Fix server workflow trigger

### ISSUE THREAD

**Issue by artemmatiushenko1** [KhrapkoVasyl/Cooka#1]
Pls, make the workflow run only when files in `server` folder were changed
```yaml
on:
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'
```
https://github.com/KhrapkoVasyl/Cooka/blob/2e890c40e2efe1544435ad7d208ab7c2955f9e17/.github/workflows/ci-server.yml#L3
